filebeat.inputs:
- type: log
  enabled: true
  paths:
  - /usr/share/filebeat/logs/*.log

output.logstash:
  hosts: ["logstash:5044"]
  
logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
  selectors: ["*"]
  level: warning