version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
        container_name: elasticsearch
        hostname: elasticsearch
        networks:
            - elknetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:7.0.0
        ports:
            - 5601:5601
        container_name: kibana
        hostname: kibana
        links:
            - elasticsearch:elasticsearch
        depends_on:
            - elasticsearch
        networks:
            - elknetwork
    logstash:
        image: logstash:7.0.0
        container_name: logstash
        hostname: logstash
        ports:
            - 5044:5044
        volumes:
            - ./logstash:/usr/share/logstash/pipeline
        links:
            - elasticsearch:elasticsearch
        depends_on:
            - elasticsearch
        networks:
            - elknetwork
networks:
    elknetwork:
        driver: bridge